//! The larger style library, written as compact recipes: Fujifilm film simulations
//! and Leica looks (inspired by, not measured from, the cameras' own), and the
//! Portraits, Landscape, Aerial, Lifestyle, Essentials, Macro and Cinematic sets.
//!
//! Units as in the Step 4–5 controls: HSL and wheel amounts in slider units
//! (−100…100), saturation / vibrance / contrast normalised (−1…1), texture in slider
//! units, film and glow 0…1.

use super::super::atmosphere::AtmosphereParams;
use super::super::grade::ColorParams;
use super::{
    film, hsl, info, texture, wheels, Style, AERIAL, AQUA, BLUE, CINEMATIC, ESSENTIALS, FILM, GREEN, HIGHLIGHTS,
    LANDSCAPE, LIFESTYLE, MACRO, MAGENTA, MIDTONES, ORANGE, PORTRAIT, PURPLE, RED, SHADOWS, YELLOW,
};

type Bands = &'static [(usize, [f32; 3])];

pub(super) struct Recipe {
    id: &'static str,
    name: &'static str,
    cat: &'static str,
    world: &'static str,
    desc: &'static str,
    protect: f32,
    swatch: [&'static str; 2],
    hsl: Bands,
    wheels: Bands,
    sat: f32,
    vib: f32,
    con: f32,
    mono: f32,
    /// Clarity, micro-texture, blemish smoothing, specular balance.
    tex: [f32; 4],
    /// Fade, highlight roll, grain, grain size.
    film: [f32; 4],
    /// Glow amount, radius, warmth.
    glow: [f32; 3],
    /// Uniform haze and its warmth.
    haze: [f32; 2],
    /// Extra grade for skin only.
    skin: Bands,
}

const BASE: Recipe = Recipe {
    id: "",
    name: "",
    cat: FILM,
    world: "Cinematic & Film Emulation",
    desc: "",
    protect: 40.0,
    swatch: ["#808080", "#c0c0c0"],
    hsl: &[],
    wheels: &[],
    sat: 0.0,
    vib: 0.0,
    con: 0.0,
    mono: 0.0,
    tex: [0.0; 4],
    film: [0.0; 4],
    glow: [0.0, 0.02, 0.5],
    haze: [0.0, 0.5],
    skin: &[],
};

// Colour-filter mixers for black and white (HSL luminance).
const NEUTRAL_BW: Bands = &[(ORANGE, [0.0, 0.0, 6.0]), (BLUE, [0.0, 0.0, -6.0])];
const YELLOW_FILTER: Bands =
    &[(ORANGE, [0.0, 0.0, 8.0]), (YELLOW, [0.0, 0.0, 10.0]), (AQUA, [0.0, 0.0, -8.0]), (BLUE, [0.0, 0.0, -18.0])];
const RED_FILTER: Bands = &[
    (RED, [0.0, 0.0, 22.0]),
    (ORANGE, [0.0, 0.0, 18.0]),
    (YELLOW, [0.0, 0.0, 8.0]),
    (GREEN, [0.0, 0.0, -10.0]),
    (AQUA, [0.0, 0.0, -25.0]),
    (BLUE, [0.0, 0.0, -38.0]),
];
const GREEN_FILTER: Bands = &[
    (RED, [0.0, 0.0, -15.0]),
    (ORANGE, [0.0, 0.0, -6.0]),
    (YELLOW, [0.0, 0.0, 10.0]),
    (GREEN, [0.0, 0.0, 22.0]),
    (BLUE, [0.0, 0.0, -6.0]),
];

const FUJI: &str = "Fujifilm-inspired Film Simulation";
const LEICA: &str = "Leica-inspired Look";

pub(super) const RECIPES: &[Recipe] = &[
    // ---- Fujifilm film simulations (inspired by) ----------------------------------------
    Recipe {
        id: "fuji-provia",
        name: "Provia / Standard",
        world: FUJI,
        desc: "Fujifilm's all-rounder: faithful colour, moderate contrast and saturation.",
        swatch: ["#5b7fb0", "#e0c9a0"],
        hsl: &[(BLUE, [0.0, 4.0, 0.0]), (GREEN, [0.0, 4.0, 0.0])],
        sat: 0.04,
        con: 0.06,
        ..BASE
    },
    Recipe {
        id: "fuji-velvia",
        name: "Velvia / Vivid",
        world: FUJI,
        desc: "Slide-film punch: deep blues, rich greens and reds, high contrast. Best for landscapes.",
        protect: 60.0,
        swatch: ["#1f4fa8", "#2e8b3a"],
        hsl: &[
            (RED, [-4.0, 18.0, -4.0]),
            (ORANGE, [0.0, 8.0, 0.0]),
            (YELLOW, [-4.0, 14.0, 0.0]),
            (GREEN, [4.0, 22.0, -6.0]),
            (AQUA, [0.0, 18.0, -4.0]),
            (BLUE, [-4.0, 22.0, -10.0]),
            (MAGENTA, [0.0, 12.0, 0.0]),
        ],
        sat: 0.18,
        con: 0.2,
        ..BASE
    },
    Recipe {
        id: "fuji-astia",
        name: "Astia / Soft",
        world: FUJI,
        desc: "Soft contrast for portraits with bright, clean blues and greens kept lively.",
        protect: 55.0,
        swatch: ["#e8c4a8", "#8cc0d8"],
        hsl: &[(ORANGE, [0.0, -4.0, 6.0]), (GREEN, [0.0, 6.0, 4.0]), (BLUE, [0.0, 8.0, 4.0])],
        sat: 0.04,
        con: -0.08,
        tex: [-5.0, 0.0, 8.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "fuji-classic-chrome",
        name: "Classic Chrome",
        world: FUJI,
        desc: "Documentary colour: muted, cyan-leaning blues, subdued reds, firm shadows, a quiet brownish warmth.",
        protect: 45.0,
        swatch: ["#5e7a80", "#b59a7a"],
        hsl: &[
            (RED, [4.0, -18.0, 0.0]),
            (ORANGE, [0.0, -10.0, 0.0]),
            (YELLOW, [-6.0, -20.0, 0.0]),
            (GREEN, [-6.0, -28.0, -4.0]),
            (AQUA, [-6.0, -10.0, 0.0]),
            (BLUE, [-8.0, -15.0, -6.0]),
        ],
        wheels: &[(SHADOWS, [195.0, 6.0, -2.0]), (HIGHLIGHTS, [45.0, 6.0, 0.0])],
        sat: -0.12,
        con: 0.14,
        film: [0.02, 0.05, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "fuji-reala-ace",
        name: "Reala Ace",
        world: FUJI,
        desc: "True-to-life colour with crisp, slightly hard tonality: an everyday negative look.",
        swatch: ["#6f8fb3", "#d9b48f"],
        hsl: &[(GREEN, [2.0, 2.0, 0.0]), (BLUE, [0.0, 4.0, 0.0])],
        sat: 0.02,
        con: 0.1,
        ..BASE
    },
    Recipe {
        id: "fuji-pro-neg-hi",
        name: "Pro Neg. Hi",
        world: FUJI,
        desc: "Portrait negative with a little extra contrast: natural skin, gently saturated backgrounds.",
        protect: 60.0,
        swatch: ["#d8b294", "#6f8a9c"],
        hsl: &[(ORANGE, [0.0, -4.0, 4.0]), (GREEN, [0.0, -6.0, 0.0])],
        con: 0.08,
        ..BASE
    },
    Recipe {
        id: "fuji-pro-neg-std",
        name: "Pro Neg. Std",
        world: FUJI,
        desc: "Flat, soft studio negative: smooth skin gradation and muted colour for later grading.",
        protect: 60.0,
        swatch: ["#d9bca6", "#9aa7ab"],
        hsl: &[(ORANGE, [0.0, -6.0, 4.0]), (GREEN, [0.0, -12.0, 0.0]), (BLUE, [0.0, -8.0, 0.0])],
        sat: -0.08,
        con: -0.12,
        ..BASE
    },
    Recipe {
        id: "fuji-classic-neg",
        name: "Classic Neg.",
        world: FUJI,
        desc: "Everyday consumer-negative feel: hard contrast, low saturation, cyan-green shadows and warm highlights.",
        protect: 40.0,
        swatch: ["#4f7a72", "#d8a878"],
        hsl: &[
            (RED, [6.0, -6.0, -4.0]),
            (ORANGE, [-2.0, -8.0, 0.0]),
            (YELLOW, [-10.0, -12.0, 0.0]),
            (GREEN, [12.0, -18.0, -4.0]),
            (AQUA, [-4.0, -6.0, 0.0]),
            (BLUE, [-8.0, -12.0, -4.0]),
        ],
        wheels: &[(SHADOWS, [175.0, 12.0, -2.0]), (HIGHLIGHTS, [38.0, 10.0, 0.0])],
        sat: -0.1,
        con: 0.18,
        film: [0.06, 0.1, 0.08, 0.3],
        ..BASE
    },
    Recipe {
        id: "fuji-nostalgic-neg",
        name: "Nostalgic Neg.",
        world: FUJI,
        desc: "American New Colour warmth: amber highlights, softened brights, rich but gentle shadows.",
        protect: 40.0,
        swatch: ["#c08850", "#6a5a4a"],
        hsl: &[(RED, [4.0, 6.0, 0.0]), (ORANGE, [2.0, 8.0, 4.0]), (YELLOW, [-6.0, 8.0, 0.0]), (BLUE, [-6.0, -10.0, 0.0])],
        wheels: &[(MIDTONES, [40.0, 6.0, 0.0]), (HIGHLIGHTS, [38.0, 16.0, 0.0])],
        con: 0.04,
        film: [0.06, 0.25, 0.08, 0.3],
        ..BASE
    },
    Recipe {
        id: "fuji-eterna",
        name: "Eterna / Cinema",
        world: FUJI,
        desc: "Motion-picture stock: very soft contrast, restrained saturation and teal-leaning shadows; made for grading.",
        protect: 45.0,
        swatch: ["#3e5a5c", "#b8a88a"],
        hsl: &[(RED, [0.0, -12.0, 0.0]), (YELLOW, [-4.0, -14.0, 0.0]), (GREEN, [0.0, -18.0, 0.0]), (BLUE, [-4.0, -10.0, 0.0])],
        wheels: &[(SHADOWS, [190.0, 10.0, 0.0])],
        sat: -0.15,
        con: -0.16,
        film: [0.08, 0.2, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "fuji-eterna-bleach",
        name: "Eterna Bleach Bypass",
        world: FUJI,
        desc: "The skipped-bleach film process: very low saturation, hard contrast, silvery highlights.",
        protect: 30.0,
        swatch: ["#50575a", "#c9c6bd"],
        sat: -0.45,
        con: 0.28,
        tex: [10.0, 8.0, 0.0, 0.0],
        film: [0.0, 0.05, 0.1, 0.3],
        ..BASE
    },
    Recipe {
        id: "fuji-acros",
        name: "Acros",
        world: FUJI,
        desc: "Fine-grained black and white with deep blacks, smooth midtones and crisp detail.",
        protect: 20.0,
        swatch: ["#111111", "#dddddd"],
        hsl: NEUTRAL_BW,
        mono: 1.0,
        con: 0.16,
        tex: [5.0, 12.0, 0.0, 0.0],
        film: [0.0, 0.05, 0.12, 0.15],
        ..BASE
    },
    Recipe {
        id: "fuji-acros-ye",
        name: "Acros + Ye filter",
        world: FUJI,
        desc: "Acros through a yellow filter: skies a touch darker, clouds and skin slightly brighter.",
        protect: 20.0,
        swatch: ["#151515", "#e0dccb"],
        hsl: YELLOW_FILTER,
        mono: 1.0,
        con: 0.16,
        tex: [5.0, 12.0, 0.0, 0.0],
        film: [0.0, 0.05, 0.12, 0.15],
        ..BASE
    },
    Recipe {
        id: "fuji-acros-r",
        name: "Acros + R filter",
        world: FUJI,
        desc: "Acros through a red filter: dramatic dark skies, luminous skin and brick, bold contrast.",
        protect: 20.0,
        swatch: ["#0c0c0c", "#eee4dc"],
        hsl: RED_FILTER,
        mono: 1.0,
        con: 0.2,
        tex: [6.0, 12.0, 0.0, 0.0],
        film: [0.0, 0.05, 0.12, 0.15],
        ..BASE
    },
    Recipe {
        id: "fuji-acros-g",
        name: "Acros + G filter",
        world: FUJI,
        desc: "Acros through a green filter: bright foliage, deeper lips and skin tones for character portraits.",
        protect: 20.0,
        swatch: ["#141414", "#dfe6dc"],
        hsl: GREEN_FILTER,
        mono: 1.0,
        con: 0.16,
        tex: [5.0, 12.0, 0.0, 0.0],
        film: [0.0, 0.05, 0.12, 0.15],
        ..BASE
    },
    Recipe {
        id: "fuji-monochrome",
        name: "Monochrome",
        world: FUJI,
        desc: "Straight black and white: neutral mix, standard contrast, no grain.",
        protect: 20.0,
        swatch: ["#262626", "#d4d4d4"],
        hsl: NEUTRAL_BW,
        mono: 1.0,
        con: 0.08,
        ..BASE
    },
    Recipe {
        id: "fuji-monochrome-ye",
        name: "Monochrome + Ye filter",
        world: FUJI,
        desc: "Standard black and white through a yellow filter.",
        protect: 20.0,
        swatch: ["#282828", "#dcd8c8"],
        hsl: YELLOW_FILTER,
        mono: 1.0,
        con: 0.08,
        ..BASE
    },
    Recipe {
        id: "fuji-monochrome-r",
        name: "Monochrome + R filter",
        world: FUJI,
        desc: "Standard black and white through a red filter: darker skies, lighter skin.",
        protect: 20.0,
        swatch: ["#202020", "#e6ddd4"],
        hsl: RED_FILTER,
        mono: 1.0,
        con: 0.1,
        ..BASE
    },
    Recipe {
        id: "fuji-monochrome-g",
        name: "Monochrome + G filter",
        world: FUJI,
        desc: "Standard black and white through a green filter: lighter foliage, richer skin.",
        protect: 20.0,
        swatch: ["#222222", "#dbe2d8"],
        hsl: GREEN_FILTER,
        mono: 1.0,
        con: 0.08,
        ..BASE
    },
    Recipe {
        id: "fuji-sepia",
        name: "Sepia",
        world: FUJI,
        desc: "Warm brown-toned monochrome, like an old print.",
        protect: 20.0,
        swatch: ["#4a3624", "#e2cfb0"],
        hsl: NEUTRAL_BW,
        mono: 1.0,
        wheels: &[(SHADOWS, [30.0, 22.0, 0.0]), (MIDTONES, [35.0, 26.0, 0.0]), (HIGHLIGHTS, [42.0, 18.0, 0.0])],
        con: 0.04,
        film: [0.06, 0.1, 0.0, 0.0],
        ..BASE
    },
    // ---- Leica looks (inspired by) -----------------------------------------------------
    Recipe {
        id: "leica-standard",
        name: "Leica Standard",
        world: LEICA,
        desc: "Leica's natural rendering: accurate colour, gentle contrast, clean highlights.",
        swatch: ["#6c7f95", "#d8c1a6"],
        con: 0.05,
        tex: [4.0, 4.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "leica-vivid",
        name: "Leica Vivid",
        world: LEICA,
        desc: "More saturated and contrasty, with bright, clear colour.",
        protect: 50.0,
        swatch: ["#2d62b8", "#e3a33b"],
        hsl: &[(RED, [0.0, 8.0, 0.0]), (GREEN, [0.0, 10.0, 0.0]), (BLUE, [0.0, 12.0, -4.0])],
        sat: 0.14,
        con: 0.14,
        tex: [6.0, 6.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "leica-natural",
        name: "Leica Natural",
        world: LEICA,
        desc: "Lower contrast and saturation: soft, true-to-life files for later grading.",
        protect: 50.0,
        swatch: ["#8395a3", "#d9c8b4"],
        sat: -0.08,
        con: -0.08,
        ..BASE
    },
    Recipe {
        id: "leica-classic",
        name: "Leica Classic",
        world: LEICA,
        desc: "Analogue-era colour: warm, slightly muted, gentle contrast and soft highlights.",
        swatch: ["#9c7a55", "#d6c4a2"],
        hsl: &[(YELLOW, [-4.0, -8.0, 0.0]), (GREEN, [-4.0, -14.0, 0.0]), (BLUE, [-4.0, -12.0, 0.0])],
        wheels: &[(HIGHLIGHTS, [40.0, 10.0, 0.0]), (SHADOWS, [30.0, 5.0, 0.0])],
        sat: -0.06,
        con: 0.02,
        film: [0.08, 0.2, 0.06, 0.25],
        ..BASE
    },
    Recipe {
        id: "leica-contemporary",
        name: "Leica Contemporary",
        world: LEICA,
        desc: "Modern and cool: clean whites, cyan-leaning shadows, restrained saturation.",
        swatch: ["#50707e", "#e6e8e8"],
        hsl: &[(ORANGE, [0.0, -6.0, 0.0]), (YELLOW, [0.0, -10.0, 0.0]), (AQUA, [0.0, 6.0, 0.0])],
        wheels: &[(SHADOWS, [200.0, 10.0, 0.0]), (HIGHLIGHTS, [210.0, 4.0, 2.0])],
        sat: -0.06,
        con: 0.08,
        ..BASE
    },
    Recipe {
        id: "leica-eternal",
        name: "Leica Eternal",
        world: LEICA,
        desc: "Cinematic: soft, muted, teal shadows and warm skin, like a motion-picture stock.",
        protect: 50.0,
        swatch: ["#35565a", "#c9a27c"],
        hsl: &[(GREEN, [-6.0, -20.0, 0.0]), (BLUE, [-6.0, -10.0, 0.0])],
        wheels: &[(SHADOWS, [190.0, 14.0, 0.0]), (HIGHLIGHTS, [35.0, 8.0, 0.0])],
        sat: -0.12,
        con: -0.06,
        film: [0.08, 0.2, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "leica-chrome",
        name: "Leica Chrome",
        world: LEICA,
        desc: "Slide-film colour: saturated, deep blues and greens, fairly firm contrast.",
        protect: 45.0,
        swatch: ["#234f86", "#c7843c"],
        hsl: &[(RED, [0.0, 10.0, 0.0]), (GREEN, [4.0, 10.0, -4.0]), (BLUE, [-4.0, 14.0, -8.0])],
        sat: 0.08,
        con: 0.12,
        ..BASE
    },
    Recipe {
        id: "leica-chrome-hc",
        name: "Leica Chrome High Contrast",
        world: LEICA,
        desc: "Leica Chrome with hard contrast and deep shadows: bold street and travel colour.",
        protect: 45.0,
        swatch: ["#162f5a", "#d68a38"],
        hsl: &[(RED, [0.0, 10.0, 0.0]), (GREEN, [4.0, 10.0, -6.0]), (BLUE, [-4.0, 14.0, -12.0])],
        sat: 0.08,
        con: 0.26,
        tex: [8.0, 6.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "leica-sepia",
        name: "Leica Sepia",
        world: LEICA,
        desc: "Warm-toned monochrome with soft, rounded highlights.",
        protect: 20.0,
        swatch: ["#503a26", "#e5d2b3"],
        hsl: NEUTRAL_BW,
        mono: 1.0,
        wheels: &[(SHADOWS, [32.0, 18.0, 0.0]), (MIDTONES, [36.0, 22.0, 0.0]), (HIGHLIGHTS, [42.0, 14.0, 0.0])],
        con: 0.06,
        ..BASE
    },
    Recipe {
        id: "leica-selenium",
        name: "Leica Selenium",
        world: LEICA,
        desc: "Selenium-toned print: cool purple-brown shadows, neutral highlights, deep blacks.",
        protect: 20.0,
        swatch: ["#2f2733", "#dedad6"],
        hsl: NEUTRAL_BW,
        mono: 1.0,
        wheels: &[(SHADOWS, [300.0, 14.0, -2.0]), (MIDTONES, [330.0, 6.0, 0.0])],
        con: 0.14,
        ..BASE
    },
    Recipe {
        id: "leica-blue",
        name: "Leica Blue",
        world: LEICA,
        desc: "Cyanotype-like blue-toned monochrome.",
        protect: 20.0,
        swatch: ["#1e3550", "#d4e0ea"],
        hsl: NEUTRAL_BW,
        mono: 1.0,
        wheels: &[(SHADOWS, [215.0, 26.0, 0.0]), (MIDTONES, [210.0, 20.0, 0.0]), (HIGHLIGHTS, [205.0, 8.0, 0.0])],
        con: 0.06,
        ..BASE
    },
    Recipe {
        id: "leica-bw-natural",
        name: "Leica B&W Natural",
        world: LEICA,
        desc: "Black and white with natural contrast and a long, smooth grey scale.",
        protect: 20.0,
        swatch: ["#2a2a2a", "#d8d8d8"],
        hsl: NEUTRAL_BW,
        mono: 1.0,
        con: 0.04,
        tex: [4.0, 8.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "leica-bw-hc",
        name: "Leica B&W High Contrast",
        world: LEICA,
        desc: "Punchy black and white: dense blacks, bright whites, a darker sky.",
        protect: 20.0,
        swatch: ["#060606", "#f2f2f2"],
        hsl: YELLOW_FILTER,
        mono: 1.0,
        con: 0.3,
        tex: [10.0, 10.0, 0.0, 0.0],
        film: [0.0, 0.0, 0.08, 0.2],
        ..BASE
    },
    // ---- Portraits & Skin ----------------------------------------------------------------
    Recipe {
        id: "porcelain-glow",
        name: "Porcelain Glow",
        cat: PORTRAIT,
        world: "Beauty & Editorial Portraiture",
        desc: "Luminous, even skin with a soft bloom and clean, slightly cool whites.",
        protect: 70.0,
        swatch: ["#f2dfd4", "#c9d6e0"],
        hsl: &[(ORANGE, [0.0, -8.0, 10.0]), (RED, [0.0, -6.0, 4.0])],
        wheels: &[(HIGHLIGHTS, [210.0, 4.0, 2.0])],
        con: -0.06,
        tex: [-10.0, 0.0, 30.0, 20.0],
        glow: [0.18, 0.03, 0.3],
        ..BASE
    },
    Recipe {
        id: "golden-skin",
        name: "Golden Skin",
        cat: PORTRAIT,
        world: "Beauty & Editorial Portraiture",
        desc: "Sun-kissed warmth on skin, honeyed highlights and softly warm shadows.",
        protect: 30.0,
        swatch: ["#d49a5e", "#f3d9a8"],
        wheels: &[(MIDTONES, [38.0, 8.0, 0.0]), (HIGHLIGHTS, [42.0, 14.0, 0.0])],
        skin: &[(ORANGE, [2.0, 8.0, 4.0])],
        vib: 0.06,
        tex: [0.0, 0.0, 15.0, 10.0],
        ..BASE
    },
    Recipe {
        id: "clean-commercial",
        name: "Clean Commercial",
        cat: PORTRAIT,
        world: "Beauty & Editorial Portraiture",
        desc: "Bright, crisp and neutral: true skin, clean whites, a touch of clarity for headshots.",
        protect: 70.0,
        swatch: ["#e9e4de", "#b3a08a"],
        hsl: &[(ORANGE, [0.0, -4.0, 4.0])],
        con: 0.06,
        tex: [6.0, 6.0, 20.0, 15.0],
        ..BASE
    },
    Recipe {
        id: "matte-portrait",
        name: "Matte Portrait",
        cat: PORTRAIT,
        world: "Beauty & Editorial Portraiture",
        desc: "Lifted, milky blacks and gentle colour: the soft matte look of modern editorial.",
        protect: 60.0,
        swatch: ["#6e6862", "#d8cfc4"],
        sat: -0.08,
        con: -0.1,
        film: [0.28, 0.2, 0.05, 0.25],
        tex: [-4.0, 0.0, 15.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "bronze-editorial",
        name: "Bronze Editorial",
        cat: PORTRAIT,
        world: "Character & High-Contrast Portraiture",
        desc: "Rich bronze skin, deep warm shadows and sculpted contrast; flattering on darker skin.",
        protect: 30.0,
        swatch: ["#6a3f22", "#c98f5c"],
        wheels: &[(SHADOWS, [28.0, 10.0, -2.0]), (HIGHLIGHTS, [40.0, 8.0, 0.0])],
        skin: &[(ORANGE, [-2.0, 10.0, 2.0]), (RED, [4.0, 6.0, 0.0])],
        con: 0.12,
        tex: [8.0, 4.0, 10.0, 25.0],
        ..BASE
    },
    Recipe {
        id: "rosy-fresh",
        name: "Rosy Fresh",
        cat: PORTRAIT,
        world: "Beauty & Editorial Portraiture",
        desc: "Healthy pink-peach complexion, fresh greens and soft, bright light.",
        protect: 40.0,
        swatch: ["#f0b4a8", "#bfe0c0"],
        hsl: &[(RED, [-4.0, 4.0, 4.0]), (GREEN, [6.0, 4.0, 6.0])],
        skin: &[(RED, [-4.0, 4.0, 2.0]), (ORANGE, [-4.0, 0.0, 4.0])],
        con: -0.04,
        tex: [-4.0, 0.0, 20.0, 10.0],
        ..BASE
    },
    Recipe {
        id: "low-key-drama",
        name: "Low-Key Drama",
        cat: PORTRAIT,
        world: "Character & High-Contrast Portraiture",
        desc: "Dark, moody portrait: deep shadows, sculpted light on the face, muted surroundings.",
        protect: 60.0,
        swatch: ["#141210", "#a0826a"],
        wheels: &[(SHADOWS, [210.0, 6.0, -8.0])],
        sat: -0.12,
        con: 0.22,
        tex: [12.0, 8.0, 0.0, 10.0],
        ..BASE
    },
    Recipe {
        id: "window-light",
        name: "Window Light",
        cat: PORTRAIT,
        world: "Beauty & Editorial Portraiture",
        desc: "Natural daylight portraits: soft, slightly cool fill, honest skin and gentle contrast.",
        protect: 60.0,
        swatch: ["#c7ced4", "#e0c4ac"],
        wheels: &[(SHADOWS, [215.0, 6.0, 0.0])],
        con: -0.04,
        tex: [0.0, 0.0, 12.0, 10.0],
        ..BASE
    },
    Recipe {
        id: "wedding-airy",
        name: "Wedding Airy",
        cat: PORTRAIT,
        world: "Beauty & Editorial Portraiture",
        desc: "Light and airy: bright pastels, creamy whites, soft greens; the fine-art wedding look.",
        protect: 55.0,
        swatch: ["#f4ede4", "#c8d8c0"],
        hsl: &[(GREEN, [12.0, -18.0, 10.0]), (YELLOW, [0.0, -10.0, 6.0]), (BLUE, [0.0, -12.0, 8.0])],
        wheels: &[(HIGHLIGHTS, [45.0, 6.0, 4.0])],
        con: -0.12,
        film: [0.12, 0.3, 0.0, 0.0],
        tex: [-6.0, 0.0, 20.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "classic-bw-portrait",
        name: "Classic B&W Portrait",
        cat: PORTRAIT,
        world: "Character & High-Contrast Portraiture",
        desc: "Timeless black-and-white portrait: glowing skin, rich blacks and fine texture.",
        protect: 20.0,
        swatch: ["#161616", "#ede6e0"],
        hsl: &[(RED, [0.0, 0.0, 10.0]), (ORANGE, [0.0, 0.0, 14.0]), (BLUE, [0.0, 0.0, -12.0])],
        mono: 1.0,
        con: 0.14,
        tex: [6.0, 10.0, 15.0, 10.0],
        ..BASE
    },
    // ---- Landscape & Nature --------------------------------------------------------------
    Recipe {
        id: "nordic-blue-hour",
        name: "Nordic Blue Hour",
        cat: LANDSCAPE,
        world: "Nature & Landscape",
        desc: "Cold, calm twilight blues with a whisper of warm light at the horizon.",
        protect: 60.0,
        swatch: ["#1f3350", "#e6b88a"],
        wheels: &[(SHADOWS, [220.0, 14.0, 0.0]), (MIDTONES, [215.0, 8.0, 0.0]), (HIGHLIGHTS, [35.0, 8.0, 0.0])],
        hsl: &[(BLUE, [0.0, 10.0, -4.0])],
        con: 0.06,
        ..BASE
    },
    Recipe {
        id: "autumn-gold",
        name: "Autumn Gold",
        cat: LANDSCAPE,
        world: "Nature & Landscape",
        desc: "Fiery oranges, golden yellows and warm light for autumn foliage.",
        protect: 60.0,
        swatch: ["#c0601c", "#e8b43a"],
        hsl: &[
            (RED, [4.0, 10.0, 0.0]),
            (ORANGE, [0.0, 20.0, 4.0]),
            (YELLOW, [-10.0, 18.0, 4.0]),
            (GREEN, [-20.0, -10.0, 0.0]),
        ],
        wheels: &[(HIGHLIGHTS, [40.0, 10.0, 0.0])],
        vib: 0.08,
        con: 0.08,
        ..BASE
    },
    Recipe {
        id: "desert-heat",
        name: "Desert Heat",
        cat: LANDSCAPE,
        world: "Nature & Landscape",
        desc: "Sun-baked warmth: terracotta sands, deep blue skies, a dry, hazy glow.",
        protect: 60.0,
        swatch: ["#c77c47", "#2a5c9e"],
        hsl: &[(ORANGE, [0.0, 16.0, 0.0]), (YELLOW, [-6.0, 6.0, 0.0]), (BLUE, [-4.0, 12.0, -8.0])],
        wheels: &[(MIDTONES, [32.0, 10.0, 0.0])],
        con: 0.1,
        haze: [0.06, 0.8],
        ..BASE
    },
    Recipe {
        id: "misty-forest",
        name: "Misty Forest",
        cat: LANDSCAPE,
        world: "Nature & Landscape",
        desc: "Muted mossy greens, soft fog and quiet contrast for woodland scenes.",
        protect: 60.0,
        swatch: ["#46594a", "#c3cbc0"],
        hsl: &[(GREEN, [-6.0, -18.0, 0.0]), (YELLOW, [-10.0, -14.0, 0.0])],
        wheels: &[(SHADOWS, [150.0, 8.0, 0.0])],
        sat: -0.08,
        con: -0.08,
        haze: [0.1, 0.4],
        film: [0.1, 0.1, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "crisp-winter",
        name: "Crisp Winter",
        cat: LANDSCAPE,
        world: "Nature & Landscape",
        desc: "Clean white snow, cold blue shadows and crisp detail.",
        protect: 60.0,
        swatch: ["#dfe9f2", "#4f78a8"],
        wheels: &[(SHADOWS, [215.0, 14.0, 0.0]), (HIGHLIGHTS, [210.0, 3.0, 3.0])],
        hsl: &[(BLUE, [0.0, 8.0, 0.0])],
        con: 0.08,
        tex: [10.0, 10.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "tropical-lagoon",
        name: "Tropical Lagoon",
        cat: LANDSCAPE,
        world: "Nature & Landscape",
        desc: "Turquoise water, lush greens and bright sunny whites.",
        protect: 60.0,
        swatch: ["#19b0b8", "#5aa845"],
        hsl: &[(AQUA, [-6.0, 24.0, 4.0]), (BLUE, [-8.0, 12.0, 0.0]), (GREEN, [4.0, 14.0, 0.0])],
        vib: 0.12,
        con: 0.06,
        ..BASE
    },
    Recipe {
        id: "mountain-drama",
        name: "Mountain Drama",
        cat: LANDSCAPE,
        world: "Nature & Landscape",
        desc: "Deep skies, strong local contrast and textured rock for epic mountain scenes.",
        protect: 60.0,
        swatch: ["#253444", "#b9b2a4"],
        hsl: &[(BLUE, [0.0, 10.0, -14.0]), (AQUA, [0.0, 0.0, -6.0])],
        con: 0.14,
        tex: [25.0, 15.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "coastal-pastel",
        name: "Coastal Pastel",
        cat: LANDSCAPE,
        world: "Nature & Landscape",
        desc: "Soft seaside pastels: pale aquas, sandy creams and lifted shadows.",
        protect: 60.0,
        swatch: ["#a8d4d4", "#efe0c8"],
        hsl: &[(AQUA, [0.0, -6.0, 10.0]), (BLUE, [0.0, -10.0, 10.0]), (YELLOW, [0.0, -10.0, 6.0])],
        con: -0.12,
        film: [0.14, 0.2, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "wildflower-meadow",
        name: "Wildflower Meadow",
        cat: LANDSCAPE,
        world: "Nature & Landscape",
        desc: "Vivid blooms in soft, warm light: rich magentas and yellows over gentle greens.",
        protect: 60.0,
        swatch: ["#c14f9a", "#e8c83a"],
        hsl: &[(MAGENTA, [0.0, 16.0, 0.0]), (PURPLE, [0.0, 14.0, 0.0]), (YELLOW, [0.0, 12.0, 4.0]), (GREEN, [6.0, -6.0, 0.0])],
        wheels: &[(HIGHLIGHTS, [45.0, 8.0, 0.0])],
        vib: 0.08,
        glow: [0.12, 0.03, 0.6],
        ..BASE
    },
    Recipe {
        id: "night-sky",
        name: "Night Sky",
        cat: LANDSCAPE,
        world: "Nature & Landscape",
        desc: "Astro and night landscapes: neutral-blue sky, crisp stars, controlled noise and warm ground light.",
        protect: 60.0,
        swatch: ["#0b1630", "#6c7fb0"],
        wheels: &[(SHADOWS, [225.0, 10.0, -2.0]), (HIGHLIGHTS, [40.0, 4.0, 0.0])],
        hsl: &[(BLUE, [0.0, 10.0, 0.0]), (PURPLE, [0.0, 8.0, 0.0])],
        con: 0.12,
        tex: [12.0, 10.0, 0.0, 0.0],
        ..BASE
    },
    // ---- Aerial ----------------------------------------------------------------------------
    Recipe {
        id: "aerial-clean",
        name: "Drone Clean",
        cat: AERIAL,
        world: "Aerial & Drone",
        desc: "Cuts the haze of altitude: clear, neutral colour and crisp detail from above.",
        protect: 60.0,
        swatch: ["#4d7aa6", "#9ab06a"],
        vib: 0.1,
        con: 0.08,
        tex: [18.0, 12.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "aerial-turquoise-coast",
        name: "Turquoise Coast",
        cat: AERIAL,
        world: "Aerial & Drone",
        desc: "Glowing shallows, white surf and golden sand seen from above.",
        protect: 60.0,
        swatch: ["#12b5c4", "#e8d6a8"],
        hsl: &[(AQUA, [-6.0, 26.0, 6.0]), (BLUE, [-6.0, 14.0, 0.0]), (YELLOW, [0.0, -6.0, 6.0])],
        vib: 0.1,
        con: 0.06,
        ..BASE
    },
    Recipe {
        id: "aerial-urban-grid",
        name: "Urban Grid",
        cat: AERIAL,
        world: "Aerial & Drone",
        desc: "City blocks and roads: cool, graphic, contrasty and slightly desaturated.",
        protect: 60.0,
        swatch: ["#3d4a58", "#c4c8cc"],
        wheels: &[(SHADOWS, [205.0, 8.0, 0.0])],
        sat: -0.1,
        con: 0.16,
        tex: [20.0, 12.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "aerial-golden",
        name: "Golden Aerial",
        cat: AERIAL,
        world: "Aerial & Drone",
        desc: "Low sun from above: long shadows, golden light raking across the land.",
        protect: 60.0,
        swatch: ["#d08a36", "#4a3a2a"],
        wheels: &[(MIDTONES, [38.0, 10.0, 0.0]), (HIGHLIGHTS, [40.0, 16.0, 0.0])],
        con: 0.12,
        glow: [0.12, 0.04, 0.8],
        ..BASE
    },
    Recipe {
        id: "aerial-patchwork",
        name: "Patchwork Fields",
        cat: AERIAL,
        world: "Aerial & Drone",
        desc: "Farmland mosaics: separated greens and yellows, rich earth and firm texture.",
        protect: 60.0,
        swatch: ["#6c9a3a", "#d8b44a"],
        hsl: &[(GREEN, [6.0, 14.0, 0.0]), (YELLOW, [-6.0, 14.0, 4.0]), (ORANGE, [0.0, 8.0, 0.0])],
        vib: 0.08,
        con: 0.08,
        tex: [14.0, 10.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "aerial-minimal",
        name: "Aerial Minimal",
        cat: AERIAL,
        world: "Aerial & Drone",
        desc: "Clean, soft and restrained for minimal compositions: pale tones, gentle colour.",
        protect: 60.0,
        swatch: ["#d6dde0", "#8fa8b0"],
        sat: -0.12,
        con: -0.1,
        film: [0.1, 0.2, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "aerial-blue-hour-city",
        name: "Blue Hour City",
        cat: AERIAL,
        world: "Aerial & Drone",
        desc: "Deep blue dusk with warm city lights glowing below.",
        protect: 60.0,
        swatch: ["#142a52", "#f0a040"],
        wheels: &[(SHADOWS, [220.0, 18.0, 0.0]), (HIGHLIGHTS, [35.0, 14.0, 0.0])],
        hsl: &[(ORANGE, [0.0, 12.0, 0.0]), (BLUE, [0.0, 12.0, -4.0])],
        con: 0.1,
        glow: [0.2, 0.012, 0.9],
        ..BASE
    },
    Recipe {
        id: "aerial-glacier",
        name: "Glacier Ice",
        cat: AERIAL,
        world: "Aerial & Drone",
        desc: "Icy cyans and whites with crisp crevasse detail.",
        protect: 60.0,
        swatch: ["#bfe4ee", "#3a6f8f"],
        hsl: &[(AQUA, [0.0, 16.0, 4.0]), (BLUE, [-6.0, 10.0, 0.0])],
        wheels: &[(SHADOWS, [205.0, 12.0, 0.0])],
        con: 0.1,
        tex: [20.0, 14.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "aerial-desert-patterns",
        name: "Desert Patterns",
        cat: AERIAL,
        world: "Aerial & Drone",
        desc: "Dunes and dry riverbeds: warm ochres, deep shadow lines and strong texture.",
        protect: 60.0,
        swatch: ["#c8834a", "#5a3a22"],
        hsl: &[(ORANGE, [0.0, 14.0, 0.0]), (YELLOW, [-6.0, 8.0, 0.0])],
        wheels: &[(SHADOWS, [25.0, 10.0, -4.0])],
        con: 0.16,
        tex: [22.0, 12.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "aerial-forest-canopy",
        name: "Forest Canopy",
        cat: AERIAL,
        world: "Aerial & Drone",
        desc: "Dense treetops: separated greens, deep shadows between crowns.",
        protect: 60.0,
        swatch: ["#1f4a2a", "#7fae52"],
        hsl: &[(GREEN, [-4.0, 10.0, -4.0]), (YELLOW, [-12.0, 6.0, 4.0])],
        con: 0.12,
        tex: [16.0, 14.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "aerial-moody-coast",
        name: "Moody Coast",
        cat: AERIAL,
        world: "Aerial & Drone",
        desc: "Stormy seas from above: dark teal water, muted land, heavy contrast.",
        protect: 60.0,
        swatch: ["#1e3c42", "#8a8f86"],
        hsl: &[(AQUA, [0.0, -10.0, -10.0]), (BLUE, [0.0, -10.0, -10.0]), (GREEN, [0.0, -20.0, 0.0])],
        wheels: &[(SHADOWS, [190.0, 12.0, -4.0])],
        sat: -0.12,
        con: 0.16,
        ..BASE
    },
    Recipe {
        id: "aerial-bw",
        name: "Aerial B&W",
        cat: AERIAL,
        world: "Aerial & Drone",
        desc: "Graphic black and white from above: shape, line and shadow.",
        protect: 20.0,
        swatch: ["#121212", "#e8e8e8"],
        hsl: RED_FILTER,
        mono: 1.0,
        con: 0.22,
        tex: [18.0, 10.0, 0.0, 0.0],
        ..BASE
    },
    // ---- Lifestyle -------------------------------------------------------------------------
    Recipe {
        id: "bright-airy",
        name: "Bright & Airy",
        cat: LIFESTYLE,
        world: "Lifestyle & Everyday",
        desc: "Clean, light-filled and soft: bright whites and gentle pastel colour.",
        protect: 55.0,
        swatch: ["#f5f1ea", "#cfdad8"],
        hsl: &[(GREEN, [10.0, -14.0, 8.0]), (YELLOW, [0.0, -10.0, 6.0])],
        con: -0.12,
        film: [0.1, 0.3, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "warm-home",
        name: "Warm Home",
        cat: LIFESTYLE,
        world: "Lifestyle & Everyday",
        desc: "Cosy interiors: warm wood, soft lamps and inviting, gentle contrast.",
        protect: 45.0,
        swatch: ["#b07a4a", "#f0dcc0"],
        wheels: &[(MIDTONES, [35.0, 10.0, 0.0]), (HIGHLIGHTS, [40.0, 10.0, 0.0])],
        con: -0.04,
        glow: [0.1, 0.03, 0.8],
        ..BASE
    },
    Recipe {
        id: "cafe-film",
        name: "Café Film",
        cat: LIFESTYLE,
        world: "Lifestyle & Everyday",
        desc: "Film-like everyday moments: warm, slightly faded, with fine grain.",
        protect: 45.0,
        swatch: ["#8a6a4e", "#d8c4a4"],
        hsl: &[(GREEN, [-6.0, -14.0, 0.0]), (BLUE, [-4.0, -10.0, 0.0])],
        wheels: &[(HIGHLIGHTS, [40.0, 10.0, 0.0])],
        film: [0.16, 0.2, 0.18, 0.3],
        ..BASE
    },
    Recipe {
        id: "sunday-morning",
        name: "Sunday Morning",
        cat: LIFESTYLE,
        world: "Lifestyle & Everyday",
        desc: "Soft morning light, creamy highlights and relaxed, low contrast.",
        protect: 55.0,
        swatch: ["#f2e4cc", "#b8b0a0"],
        wheels: &[(HIGHLIGHTS, [45.0, 10.0, 2.0])],
        con: -0.1,
        glow: [0.14, 0.04, 0.6],
        ..BASE
    },
    Recipe {
        id: "coastal-living",
        name: "Coastal Living",
        cat: LIFESTYLE,
        world: "Lifestyle & Everyday",
        desc: "Breezy blues, sandy neutrals and clean daylight.",
        protect: 55.0,
        swatch: ["#7fb2c8", "#e8dcc4"],
        hsl: &[(BLUE, [-6.0, 6.0, 6.0]), (AQUA, [0.0, 8.0, 4.0]), (ORANGE, [0.0, -4.0, 4.0])],
        con: -0.04,
        ..BASE
    },
    Recipe {
        id: "street-candid",
        name: "Street Candid",
        cat: LIFESTYLE,
        world: "Lifestyle & Everyday",
        desc: "Gritty city colour: muted palette, punchy contrast and texture.",
        protect: 45.0,
        swatch: ["#4a4e52", "#b89a70"],
        sat: -0.14,
        con: 0.18,
        tex: [14.0, 10.0, 0.0, 0.0],
        film: [0.0, 0.05, 0.12, 0.3],
        ..BASE
    },
    Recipe {
        id: "summer-fade",
        name: "Summer Fade",
        cat: LIFESTYLE,
        world: "Lifestyle & Everyday",
        desc: "Sun-bleached holiday colour: warm, faded, slightly overexposed.",
        protect: 45.0,
        swatch: ["#e8c09a", "#8ec4d0"],
        wheels: &[(HIGHLIGHTS, [40.0, 12.0, 4.0]), (SHADOWS, [190.0, 8.0, 0.0])],
        con: -0.08,
        film: [0.2, 0.3, 0.06, 0.25],
        ..BASE
    },
    Recipe {
        id: "cozy-tungsten",
        name: "Cozy Tungsten",
        cat: LIFESTYLE,
        world: "Lifestyle & Everyday",
        desc: "Evening indoors: amber lamplight, deep warm shadows and a soft glow.",
        protect: 40.0,
        swatch: ["#6a3a18", "#f0a850"],
        wheels: &[(SHADOWS, [30.0, 10.0, -2.0]), (MIDTONES, [34.0, 12.0, 0.0])],
        con: 0.06,
        glow: [0.2, 0.02, 1.0],
        ..BASE
    },
    Recipe {
        id: "food-fresh",
        name: "Food Fresh",
        cat: LIFESTYLE,
        world: "Lifestyle & Everyday",
        desc: "Appetising food: fresh greens, rich reds, clean whites and crisp texture.",
        protect: 20.0,
        swatch: ["#c8402a", "#6aa83a"],
        hsl: &[(RED, [0.0, 10.0, 0.0]), (ORANGE, [0.0, 10.0, 0.0]), (GREEN, [6.0, 12.0, 4.0])],
        vib: 0.1,
        con: 0.06,
        tex: [12.0, 14.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "travel-journal",
        name: "Travel Journal",
        cat: LIFESTYLE,
        world: "Lifestyle & Everyday",
        desc: "Vivid but natural travel colour with warm light and a hint of film.",
        protect: 45.0,
        swatch: ["#d08a4a", "#3a7ab0"],
        hsl: &[(BLUE, [-4.0, 8.0, -4.0]), (ORANGE, [0.0, 8.0, 0.0])],
        wheels: &[(HIGHLIGHTS, [40.0, 8.0, 0.0])],
        vib: 0.1,
        con: 0.08,
        film: [0.04, 0.1, 0.06, 0.25],
        ..BASE
    },
    Recipe {
        id: "urban-pastel",
        name: "Urban Pastel",
        cat: LIFESTYLE,
        world: "Lifestyle & Everyday",
        desc: "Candy-coloured city: soft pinks, mint and sky blue with lifted shadows.",
        protect: 50.0,
        swatch: ["#f0b8c8", "#a8e0d0"],
        hsl: &[(MAGENTA, [0.0, -6.0, 10.0]), (AQUA, [-6.0, -4.0, 10.0]), (BLUE, [0.0, -8.0, 10.0])],
        con: -0.12,
        film: [0.16, 0.2, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "soft-matte-life",
        name: "Soft Matte",
        cat: LIFESTYLE,
        world: "Lifestyle & Everyday",
        desc: "Muted, matte everyday look: lifted blacks and quiet colour for a cohesive feed.",
        protect: 50.0,
        swatch: ["#7a746c", "#d4ccc0"],
        sat: -0.12,
        con: -0.06,
        film: [0.26, 0.15, 0.04, 0.25],
        ..BASE
    },
    // ---- Essentials ------------------------------------------------------------------------
    Recipe {
        id: "essential-natural",
        name: "Natural",
        cat: ESSENTIALS,
        world: "Essentials",
        desc: "A gentle starting point: a little contrast and vibrance, nothing more.",
        protect: 60.0,
        swatch: ["#8a9aa8", "#d4c0a8"],
        vib: 0.08,
        con: 0.04,
        ..BASE
    },
    Recipe {
        id: "essential-clean-pop",
        name: "Clean Pop",
        cat: ESSENTIALS,
        world: "Essentials",
        desc: "Clear, lively colour with crisp midtones.",
        protect: 60.0,
        swatch: ["#3a7ac8", "#f0c040"],
        vib: 0.16,
        con: 0.08,
        tex: [8.0, 6.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "essential-punchy",
        name: "Punchy",
        cat: ESSENTIALS,
        world: "Essentials",
        desc: "Bold contrast and saturation for colour that jumps off the screen.",
        protect: 60.0,
        swatch: ["#c8202a", "#1a4ab0"],
        sat: 0.14,
        con: 0.2,
        tex: [10.0, 6.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "essential-warm",
        name: "Warm Up",
        cat: ESSENTIALS,
        world: "Essentials",
        desc: "A gentle golden warmth across the image.",
        protect: 50.0,
        swatch: ["#e0a060", "#f4dcb8"],
        wheels: &[(MIDTONES, [40.0, 8.0, 0.0]), (HIGHLIGHTS, [42.0, 8.0, 0.0])],
        ..BASE
    },
    Recipe {
        id: "essential-cool",
        name: "Cool Down",
        cat: ESSENTIALS,
        world: "Essentials",
        desc: "A calm, cooler balance with clean blue shadows.",
        protect: 50.0,
        swatch: ["#5a80b0", "#d8e4ee"],
        wheels: &[(SHADOWS, [215.0, 10.0, 0.0]), (MIDTONES, [210.0, 5.0, 0.0])],
        ..BASE
    },
    Recipe {
        id: "essential-crisp",
        name: "Crisp Detail",
        cat: ESSENTIALS,
        world: "Essentials",
        desc: "Sharper-looking texture and midtone clarity without harsh contrast.",
        protect: 70.0,
        swatch: ["#505a64", "#c8ccd0"],
        tex: [22.0, 18.0, 0.0, 0.0],
        con: 0.04,
        ..BASE
    },
    Recipe {
        id: "essential-high-contrast",
        name: "High Contrast",
        cat: ESSENTIALS,
        world: "Essentials",
        desc: "Deeper blacks and brighter whites.",
        protect: 60.0,
        swatch: ["#101010", "#f0f0f0"],
        con: 0.26,
        ..BASE
    },
    Recipe {
        id: "essential-low-contrast",
        name: "Low Contrast",
        cat: ESSENTIALS,
        world: "Essentials",
        desc: "Softer, flatter tones that hold detail in shadows and highlights.",
        protect: 60.0,
        swatch: ["#6a6a6a", "#b8b8b8"],
        con: -0.2,
        film: [0.06, 0.2, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "essential-vivid",
        name: "Vivid Colour",
        cat: ESSENTIALS,
        world: "Essentials",
        desc: "Stronger colour everywhere, with skin kept natural.",
        protect: 80.0,
        swatch: ["#e03a8a", "#2ab0a0"],
        sat: 0.2,
        vib: 0.1,
        ..BASE
    },
    Recipe {
        id: "essential-muted",
        name: "Muted Colour",
        cat: ESSENTIALS,
        world: "Essentials",
        desc: "Quieter, understated colour.",
        protect: 50.0,
        swatch: ["#8a8a80", "#b0a898"],
        sat: -0.22,
        ..BASE
    },
    Recipe {
        id: "essential-bw",
        name: "B&W Classic",
        cat: ESSENTIALS,
        world: "Essentials",
        desc: "A classic black-and-white conversion with a yellow-filter sky.",
        protect: 20.0,
        swatch: ["#1a1a1a", "#e4e4e4"],
        hsl: YELLOW_FILTER,
        mono: 1.0,
        con: 0.12,
        ..BASE
    },
    Recipe {
        id: "essential-bw-soft",
        name: "B&W Soft",
        cat: ESSENTIALS,
        world: "Essentials",
        desc: "Gentle, low-contrast black and white with open shadows.",
        protect: 20.0,
        swatch: ["#4a4a4a", "#dcdcdc"],
        hsl: NEUTRAL_BW,
        mono: 1.0,
        con: -0.1,
        film: [0.1, 0.2, 0.06, 0.2],
        ..BASE
    },
    // ---- Macro -----------------------------------------------------------------------------
    Recipe {
        id: "macro-clean",
        name: "Macro Clean",
        cat: MACRO,
        world: "Macro & Close-up",
        desc: "True colour with fine detail brought forward and smooth backgrounds kept smooth.",
        protect: 60.0,
        swatch: ["#6a9a4a", "#e0d0a0"],
        vib: 0.08,
        tex: [6.0, 20.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "macro-petal-soft",
        name: "Petal Soft",
        cat: MACRO,
        world: "Macro & Close-up",
        desc: "Dreamy flowers: soft glow, pastel colour and gentle contrast.",
        protect: 60.0,
        swatch: ["#f0c0d8", "#e8f0d8"],
        hsl: &[(MAGENTA, [0.0, -4.0, 8.0]), (RED, [0.0, -6.0, 6.0]), (GREEN, [8.0, -14.0, 8.0])],
        con: -0.12,
        glow: [0.22, 0.03, 0.4],
        film: [0.1, 0.25, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "macro-dewdrop",
        name: "Dewdrop Fresh",
        cat: MACRO,
        world: "Macro & Close-up",
        desc: "Morning freshness: cool, sparkling highlights and vivid greens.",
        protect: 60.0,
        swatch: ["#48a060", "#d8f0f4"],
        hsl: &[(GREEN, [4.0, 12.0, 4.0]), (AQUA, [0.0, 10.0, 0.0])],
        wheels: &[(SHADOWS, [190.0, 8.0, 0.0])],
        tex: [8.0, 18.0, 0.0, 0.0],
        con: 0.06,
        ..BASE
    },
    Recipe {
        id: "macro-insect-detail",
        name: "Insect Detail",
        cat: MACRO,
        world: "Macro & Close-up",
        desc: "Maximum fine texture and micro-contrast for insects and small creatures.",
        protect: 70.0,
        swatch: ["#3a4a2a", "#c8a040"],
        tex: [16.0, 30.0, 0.0, 0.0],
        con: 0.1,
        vib: 0.06,
        ..BASE
    },
    Recipe {
        id: "macro-botanical-dark",
        name: "Botanical Dark",
        cat: MACRO,
        world: "Macro & Close-up",
        desc: "Dutch-still-life mood: deep, dark backgrounds and rich, glowing subjects.",
        protect: 60.0,
        swatch: ["#101410", "#c05070"],
        wheels: &[(SHADOWS, [150.0, 6.0, -10.0])],
        sat: 0.04,
        con: 0.2,
        tex: [8.0, 12.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "macro-pastel-bloom",
        name: "Pastel Bloom",
        cat: MACRO,
        world: "Macro & Close-up",
        desc: "Light, airy pastels with lifted shadows for spring flowers.",
        protect: 60.0,
        swatch: ["#f4d0e0", "#d0e8f0"],
        hsl: &[(GREEN, [10.0, -20.0, 10.0]), (YELLOW, [0.0, -10.0, 8.0])],
        con: -0.14,
        film: [0.16, 0.3, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "macro-leaf-glow",
        name: "Leaf Glow",
        cat: MACRO,
        world: "Macro & Close-up",
        desc: "Backlit leaves: luminous yellow-greens and a warm glow.",
        protect: 60.0,
        swatch: ["#a8c830", "#f0d060"],
        hsl: &[(GREEN, [-8.0, 12.0, 8.0]), (YELLOW, [-6.0, 14.0, 6.0])],
        glow: [0.18, 0.03, 0.8],
        ..BASE
    },
    Recipe {
        id: "macro-texture-pop",
        name: "Texture Pop",
        cat: MACRO,
        world: "Macro & Close-up",
        desc: "Surfaces and patterns: strong clarity, micro-contrast and slightly muted colour.",
        protect: 70.0,
        swatch: ["#5a4a3a", "#b8a890"],
        sat: -0.08,
        con: 0.1,
        tex: [26.0, 26.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "macro-autumn-leaf",
        name: "Autumn Leaf",
        cat: MACRO,
        world: "Macro & Close-up",
        desc: "Close-up autumn colour: glowing reds and oranges, warm and rich.",
        protect: 60.0,
        swatch: ["#c04418", "#e89a30"],
        hsl: &[(RED, [0.0, 12.0, 0.0]), (ORANGE, [0.0, 16.0, 4.0]), (YELLOW, [-8.0, 10.0, 0.0])],
        wheels: &[(HIGHLIGHTS, [38.0, 8.0, 0.0])],
        tex: [6.0, 14.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "macro-water-blue",
        name: "Water Drop Blue",
        cat: MACRO,
        world: "Macro & Close-up",
        desc: "Cool blues and crystal-clear droplets.",
        protect: 60.0,
        swatch: ["#2a6ab0", "#c8e4f4"],
        hsl: &[(BLUE, [0.0, 12.0, 0.0]), (AQUA, [0.0, 12.0, 4.0])],
        wheels: &[(SHADOWS, [215.0, 12.0, 0.0])],
        tex: [6.0, 16.0, 0.0, 0.0],
        con: 0.06,
        ..BASE
    },
    Recipe {
        id: "macro-product",
        name: "Studio Product",
        cat: MACRO,
        world: "Macro & Close-up",
        desc: "Clean catalogue close-ups: neutral whites, accurate colour, crisp edges.",
        protect: 60.0,
        swatch: ["#f4f4f4", "#9aa0a8"],
        con: 0.06,
        tex: [10.0, 14.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "macro-mono",
        name: "Mono Macro",
        cat: MACRO,
        world: "Macro & Close-up",
        desc: "Black-and-white close-ups that celebrate form and texture.",
        protect: 20.0,
        swatch: ["#141414", "#e0e0e0"],
        hsl: GREEN_FILTER,
        mono: 1.0,
        con: 0.16,
        tex: [14.0, 20.0, 0.0, 0.0],
        ..BASE
    },
    // ---- Cinematic -------------------------------------------------------------------------
    Recipe {
        id: "blockbuster",
        name: "Blockbuster",
        cat: CINEMATIC,
        world: "Cinematic & Film Emulation",
        desc: "Big-screen action grade: strong teal shadows, warm skin, heavy contrast.",
        protect: 45.0,
        swatch: ["#0f4a52", "#e08a4a"],
        wheels: &[(SHADOWS, [190.0, 22.0, -2.0]), (HIGHLIGHTS, [32.0, 16.0, 0.0])],
        hsl: &[(GREEN, [10.0, -20.0, 0.0]), (BLUE, [-10.0, 6.0, 0.0])],
        con: 0.2,
        tex: [10.0, 6.0, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "neo-noir",
        name: "Neo-Noir",
        cat: CINEMATIC,
        world: "Cinematic & Film Emulation",
        desc: "Dark, desaturated crime-drama look with cold greens and hard shadows.",
        protect: 45.0,
        swatch: ["#0e1612", "#6e8078"],
        wheels: &[(SHADOWS, [160.0, 12.0, -6.0]), (MIDTONES, [170.0, 6.0, 0.0])],
        sat: -0.3,
        con: 0.24,
        film: [0.0, 0.05, 0.1, 0.35],
        ..BASE
    },
    Recipe {
        id: "western-dust",
        name: "Western Dust",
        cat: CINEMATIC,
        world: "Cinematic & Film Emulation",
        desc: "Sun-scorched frontier: dusty ambers, faded blacks, grain.",
        protect: 40.0,
        swatch: ["#a0703a", "#e0c89a"],
        wheels: &[(MIDTONES, [35.0, 14.0, 0.0]), (HIGHLIGHTS, [40.0, 12.0, 0.0])],
        sat: -0.1,
        con: 0.08,
        film: [0.16, 0.2, 0.2, 0.4],
        haze: [0.06, 0.9],
        ..BASE
    },
    Recipe {
        id: "nordic-noir",
        name: "Nordic Noir",
        cat: CINEMATIC,
        world: "Cinematic & Film Emulation",
        desc: "Scandinavian drama: cold, grey-blue, muted and bleak.",
        protect: 45.0,
        swatch: ["#34404a", "#a8b0b4"],
        wheels: &[(SHADOWS, [210.0, 12.0, -2.0]), (MIDTONES, [205.0, 8.0, 0.0])],
        sat: -0.3,
        con: 0.06,
        film: [0.08, 0.1, 0.0, 0.0],
        ..BASE
    },
    Recipe {
        id: "retro-70s",
        name: "Retro 70s",
        cat: CINEMATIC,
        world: "Cinematic & Film Emulation",
        desc: "Seventies film: warm browns, mustard yellows, faded blacks and grain.",
        protect: 40.0,
        swatch: ["#8a5a28", "#d8b050"],
        hsl: &[(YELLOW, [-8.0, 10.0, 0.0]), (GREEN, [-14.0, -16.0, 0.0]), (BLUE, [-6.0, -18.0, 0.0])],
        wheels: &[(SHADOWS, [30.0, 10.0, 0.0]), (HIGHLIGHTS, [45.0, 12.0, 0.0])],
        film: [0.2, 0.2, 0.22, 0.4],
        ..BASE
    },
    Recipe {
        id: "neon-rain",
        name: "Neon Rain",
        cat: CINEMATIC,
        world: "Cinematic & Film Emulation",
        desc: "Rain-soaked city nights: magenta and cyan neon, deep blacks, glowing lights.",
        protect: 45.0,
        swatch: ["#d02a8a", "#18b8d8"],
        hsl: &[(MAGENTA, [0.0, 18.0, 0.0]), (PURPLE, [0.0, 14.0, 0.0]), (AQUA, [0.0, 16.0, 0.0])],
        wheels: &[(SHADOWS, [230.0, 16.0, -4.0])],
        con: 0.14,
        glow: [0.3, 0.012, 0.2],
        ..BASE
    },
    Recipe {
        id: "war-epic",
        name: "War Epic",
        cat: CINEMATIC,
        world: "Cinematic & Film Emulation",
        desc: "Drained colour, gritty contrast and cold highlights, like a war film.",
        protect: 35.0,
        swatch: ["#4a4c42", "#b0b0a4"],
        sat: -0.4,
        con: 0.2,
        wheels: &[(HIGHLIGHTS, [200.0, 6.0, 0.0])],
        tex: [14.0, 10.0, 0.0, 0.0],
        film: [0.0, 0.05, 0.16, 0.35],
        ..BASE
    },
    Recipe {
        id: "romance-glow",
        name: "Romance Glow",
        cat: CINEMATIC,
        world: "Cinematic & Film Emulation",
        desc: "Warm, soft and dreamy: diffused highlights and gentle rose-gold tones.",
        protect: 50.0,
        swatch: ["#e0a090", "#f4e0c8"],
        wheels: &[(HIGHLIGHTS, [25.0, 12.0, 2.0]), (MIDTONES, [20.0, 6.0, 0.0])],
        con: -0.08,
        glow: [0.28, 0.04, 0.7],
        ..BASE
    },
    Recipe {
        id: "arthouse-muted",
        name: "Arthouse Muted",
        cat: CINEMATIC,
        world: "Cinematic & Film Emulation",
        desc: "Quiet, painterly independent-film palette: soft contrast, olive and dusty tones.",
        protect: 45.0,
        swatch: ["#6a6a4a", "#c4b89a"],
        hsl: &[(GREEN, [-10.0, -20.0, 0.0]), (BLUE, [-6.0, -20.0, 0.0]), (RED, [0.0, -10.0, 0.0])],
        sat: -0.12,
        con: -0.06,
        film: [0.14, 0.2, 0.08, 0.3],
        ..BASE
    },
];

pub(super) fn build(r: &Recipe) -> Style {
    Style {
        info: info(r.id, r.name, r.cat, r.world, r.desc, r.protect, r.swatch),
        texture: texture(r.tex[0], r.tex[1], r.tex[2], r.tex[3]),
        scene: ColorParams {
            hsl: hsl(r.hsl),
            wheels: wheels(r.wheels),
            saturation: r.sat,
            vibrance: r.vib,
            contrast: r.con,
            mono: r.mono,
        },
        skin: ColorParams { hsl: hsl(r.skin), ..Default::default() },
        atmosphere: AtmosphereParams {
            glow: r.glow[0],
            glow_radius: r.glow[1],
            glow_warmth: r.glow[2],
            haze: r.haze[0],
            haze_warmth: r.haze[1],
            ..Default::default()
        },
        film: film(r.film[0], r.film[1], r.film[2], r.film[3]),
    }
}
